from enum import Enum

TITLE = "Three Card Poker"
SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 800
FPS = 60
TEXT_LIGHT_COLOR = (255, 255, 255) #FFFFFF
BG_COLOR = (180, 120, 200) #B478C8
ANTE_CHIP_POS = (SCREEN_WIDTH / 2 - 105, SCREEN_HEIGHT / 2 - 60)
PAIR_PLUS_CHIP_POS = (SCREEN_WIDTH / 2 + 26, SCREEN_HEIGHT / 2 - 60)
PLAY_CHIP_POS = (SCREEN_WIDTH / 2 - 40, SCREEN_HEIGHT / 2 + 70)
PLAY_CARD_POS = (SCREEN_WIDTH / 2 - 80, SCREEN_HEIGHT / 2 + 55)
HAND_RANKING_TEXT_POS = (SCREEN_WIDTH / 2, SCREEN_HEIGHT - 18)

HAND_PLAYER_CARD_POS = [
    (SCREEN_WIDTH / 2 - 185, SCREEN_HEIGHT / 2 + 200),
    (SCREEN_WIDTH / 2 - 55, SCREEN_HEIGHT / 2 + 200),
    (SCREEN_WIDTH / 2 + 75, SCREEN_HEIGHT / 2 + 200)
]

HAND_DEALER_CARD_POS = [
    (SCREEN_WIDTH / 2 - 185, SCREEN_HEIGHT / 2 - 360),
    (SCREEN_WIDTH / 2 - 55, SCREEN_HEIGHT / 2 - 360),
    (SCREEN_WIDTH / 2 + 75, SCREEN_HEIGHT / 2 - 360)
]

class GameState(Enum):
    """
    Enum für alle möglichen Zustände des Spiels.
    """

    MENU = "MENU"
    ANTE = "ANTE"
    PAIR_PLUS = "PAIR_PLUS"
    CARD_DRAWING = "CARD_DRAWING"
    PLAY_OR_FOLD = "PLAY_OR_FOLD"
    FOLD = "FOLD"