from enum import Enum

TITLE = "Three Card Poker"
SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 800
FPS = 60
START_BALANCE = 40
TEXT_LIGHT_COLOR = (255, 255, 255) #FFFFFF
TEXT_WIN_COLOR = (130, 200, 120) #82C878
TEXT_LOSE_COLOR = (230, 80, 80) #E65050
BG_COLOR = (180, 120, 200) #B478C8
ANTE_CHIP_POS = (SCREEN_WIDTH / 2 - 105, SCREEN_HEIGHT / 2 - 60)
PAIR_PLUS_CHIP_POS = (SCREEN_WIDTH / 2 + 26, SCREEN_HEIGHT / 2 - 60)
PLAY_CHIP_POS = (SCREEN_WIDTH / 2 - 40, SCREEN_HEIGHT / 2 + 70)
HAND_PLAYER_RANKING_TEXT_POS = (SCREEN_WIDTH / 2, SCREEN_HEIGHT - 18)
HAND_DEALER_RANKING_TEXT_POS = (SCREEN_WIDTH / 2, 18)

HAND_PLAYER_CARD_POS = [
    (SCREEN_WIDTH / 2 - 185, SCREEN_HEIGHT / 2 + 200),
    (SCREEN_WIDTH / 2 - 55, SCREEN_HEIGHT / 2 + 200),
    (SCREEN_WIDTH / 2 + 75, SCREEN_HEIGHT / 2 + 200)
]

HAND_DEALER_CARD_POS = [
    (SCREEN_WIDTH / 2 - 185, SCREEN_HEIGHT / 2 - 360),
    (SCREEN_WIDTH / 2 - 55, SCREEN_HEIGHT / 2 - 360),
    (SCREEN_WIDTH / 2 + 75, SCREEN_HEIGHT / 2 - 360)
]

HAND_PLAY_CARD_POS = [
    (SCREEN_WIDTH / 2 - 85, SCREEN_HEIGHT / 2 + 50),
    (SCREEN_WIDTH / 2 - 80, SCREEN_HEIGHT / 2 + 55),
    (SCREEN_WIDTH / 2 - 75, SCREEN_HEIGHT / 2 + 60)
]

HAND_REVEAL_CARD_POS = [
    (SCREEN_WIDTH / 2 + 135, SCREEN_HEIGHT / 2 - 80),
    (SCREEN_WIDTH / 2 + 160, SCREEN_HEIGHT / 2 - 90),
    (SCREEN_WIDTH / 2 + 185, SCREEN_HEIGHT / 2 - 100)
]

class GameState(Enum):
    """
    Enum für alle möglichen Zustände des Spiels.
    """

    MENU = "MENU"
    ANTE = "ANTE"
    PAIR_PLUS = "PAIR_PLUS"
    CARD_DRAWING = "CARD_DRAWING"
    PLAY_OR_FOLD = "PLAY_OR_FOLD"
    FOLD = "FOLD"
    PLAY = "PLAY"
    REVEAL = "REVEAL"
    PAYOUT = "PAYOUT"
    GAME_OVER = "GAME_OVER"